### ISSUE TITLE
Suggestions for creating background images using cover

### ISSUE THREAD

**Issue by ianpetzer** [imgix/ember-cli-imgix#19]
Hi there,

I was just wondering if you had any advice on how to use this library to create background images?

[For example on this page,](https://www.timbuktutravel.com/countries) we have a grid of images that need to grow to fit to the browser and each of the images is set as a background image. Is there any way I can use this library to create those background images, correctly sized to their containing divs (which as sized using an aspect ratio), with the correct DPR etc.

Thanks for any suggestions

**Comment by paulstraw** [comment]
Hey @ianpetzer. In this case, it might make sense to add an absolutely-positioned `img` element to act as the background. I've been enjoying that solution for responsive background images lately. Otherwise, you tend to end up with a _lot_ of overly-specific media queries defining which `background-image` to load when.

I'm going to close this, but feel free to reopen if you have any more questions!
