### ISSUE TITLE
Securing URLs

### ISSUE THREAD

**Issue by sgasser** [imgix/ember-cli-imgix#4]
Hi,

I'm using imgix with proxy as source.
How could I secure my images?

**Comment by paulstraw** [comment]
Hey @sgasser, Web Proxy Sources can't actually be used with frontend JavaScript, as they require signed images. Since signing images on the frontend would expose your signing key, it would be very insecure. If you want to keep using a Web Proxy Source, you'll need to generate signed URLs on the backend and pass them to your Ember frontend. [imgix-core-js](https://github.com/imgix/imgix-core-js) provides signing functionality, if you want to integrate that. Feel free to reopen this if you have any further questions, and I'll be happy to help!
